### PR TITLE
Feature/sensor

### PR DESCRIPTION
**Pull request by rezendegc**
This PR allows to set the GameDecoration to be a sensor, so it have a collision box but dont stop player from moving. It's useful for stuff like spikes on floor, make player lose life when stepping on some floor, etc...

### CODE REVIEW

**Comment by rezendegc** [comment]
Thinking about this PR now, maybe the onContact should be triggered on `isCollision` method, so you don't have to call two methods everytime somethings moves... But really not sure, I'd appreciate an opinion :d

**Comment by RafaelBarbosatec** [comment]
Is true, i think that is better in `isCollision` method.

**Comment by rezendegc** [comment]
I have made `isCollision` call triggerSensors but keep it, in case someone wants to only trigger the sensors without checking for collisions... Also i have implemented an spike in the example, to be more clear of the idea behind sensors

**Comment by rezendegc** [comment]
Wel... i don't see many things missings now (that should be on the framework)... give me a heads up if you need help with any other implementations, i might create my own game to discover what is missing

**Comment by RafaelBarbosatec** [comment]
Thanks again for the contribution!
I think the basic features I imagined we already have. The next step would be integration with Tiled to facilitate the construction of maps.

**Comment by RafaelBarbosatec** [comment]
Thinking a little better about this PR. The `void onContact(collision)` method will only be called when the player is in motion. Is correct?

**Comment by rezendegc** [comment]
Currently, yes. Depending on how the person wants the `triggerSensors()` on update method to be checked everytime, but i think it being checked on player movement is enough for most cases... Do you think it should only be called on `update()` of the game, no matter what?

**Comment by RafaelBarbosatec** [comment]
I think it's OK!

**Pull request merged**
