### PR TITLE
Option for using to enable diagonal input events.

### PR DESCRIPTION
**Pull request by shinriyo**
# Description

FYI:
Update joystick.dart #433

and also added for joystick

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I open this PR to the `develop` branch.
- [x] I have added a description of the change under `[next]` in `CHANGELOG.md`.
- [x] I ran `flutter format --set-exit-if-changed --dry-run .` and has success.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in `CHANGELOG.md`).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by shinriyo** [comment]
Should I change to face for the `develop` branch?

**Comment by shinriyo** [comment]
Failed? why?

**Comment by shinriyo** [comment]
`dart format --set-exit-if-changed .` command is better for check.

**Comment by RafaelBarbosatec** [comment]
Yes, I need update de PR template to use this dart command

**Comment by shinriyo** [comment]
@RafaelBarbosatec I fix the PR for the PR template there.
Update pull_request_template.md #435

**Comment by shinriyo** [comment]
Thank you for meging.

**Pull request merged**
