### PR TITLE
Improvement on camera

### PR DESCRIPTION
**Pull request by rezendegc**
When dealing with the camera i had much trouble because the way it's implemented... When moving the camera the player would move together and when moving the player you had to sometimes move the camera instead, which is wrong by definition, the camera shouldn't influence on the position of anything on the world. So i rewrote almost everything related to camera and position to only have one position (which is relative to the world) and actually use the isHud method provided by Flame... Hope you can review the PR and maybe accept, i think it'll be much easier to handle camera movements from now on :)

### CODE REVIEW

**Comment by rezendegc** [comment]
Please, if you agree with the changes made make a comment here so i update the docs too before you merge

**Comment by rezendegc** [comment]
any thoughts on it? @RafaelBarbosatec ...

**Comment by RafaelBarbosatec** [comment]
Thank you for your contribution. I will be analyzing more calmly ;-)

**Comment by RafaelBarbosatec** [comment]
Great Job! @rezendegc !!!!!
I just didn't understand what this does exactly:
@override
  void renderComponent(Canvas canvas, Component comp) {
    if (!comp.loaded()) {
      return;
    }
    canvas.save();
    if (!comp.isHud()) {
      canvas.translate(-gameCamera.position.x, -gameCamera.position.y);
    }
    comp.render(canvas);
    canvas.restore();
  }

**Comment by RafaelBarbosatec** [comment]
Understanding this part better and correcting these conflicts I will be completing your PR. Thank you

**Comment by RafaelBarbosatec** [comment]
> Great Job! @rezendegc !!!!!
> I just didn't understand what this does exactly:
> @override
> void renderComponent(Canvas canvas, Component comp) {
> if (!comp.loaded()) {
> return;
> }
> canvas.save();
> if (!comp.isHud()) {
> canvas.translate(-gameCamera.position.x, -gameCamera.position.y);
> }
> comp.render(canvas);
> canvas.restore();
> }

Now I understand. all the movement of the components you did here on the canvas translate. Good!

**Comment by rezendegc** [comment]
Basically all it does is move the canvas to where the gameCamera position is.. It doesn't move if the component is HUD, so that you can draw relatively to the screen. I'll fix the conflicts :)

**Comment by rezendegc** [comment]
All set now... Please notice that this will be a breaking change... everything that used positionInWorld will break, but using position should fix it

**Comment by RafaelBarbosatec** [comment]
Great! 
Thanks again for the contribution. this camera system was much cleaner!
I will notify BREAKING CHANGE

**Pull request merged**
