### PR TITLE
Fix typo in some params

### PR DESCRIPTION
**Pull request by KyleKun**

### CODE REVIEW

**Comment by RafaelBarbosatec** [comment]
Thanks so much!

**Comment by RafaelBarbosatec** [comment]
Thanks so much!

Could you change the branch target to develop?

**Comment by KyleKun** [comment]
> Thanks so much!
> 
> Could you change the branch target to develop?

Oh, I commited directly to develop, my bad
Guess we don't need a PR then

**Comment by RafaelBarbosatec** [comment]
No problem 😊🤓

**Pull request closed without merging**
