### PR TITLE
Spine branch

### PR DESCRIPTION
**Pull request by zhangyc**
# Description

Support spine

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I open this PR to the `develop` branch.
- [x] I have added a description of the change under `[next]` in `CHANGELOG.md`.
- [x] I ran `flutter format --set-exit-if-changed --dry-run .` and has success.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in `CHANGELOG.md`).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by RafaelBarbosatec** [comment]
Wow ! This is awesome @zhangyc! Congratulations for this implementation! I loved it! 🥰 
I agree with @KyleKun !
This implementation could be a great package to give support to Spine in Bonfire! `bonfire_spine` or thing like that!
You starting this project I will love contributing!
I really think that amazing. I didn’t know this `Spine` yet.

Good job @zhangyc !

**Comment by zhangyc** [comment]
So, directly develop a separate dependency package?


| |
zhangyc
Android
|
|
***@***.***
|
---- Replied Message ----
| From | Rafael Almeida ***@***.***> |
| Date | 10/18/2022 09:38 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [RafaelBarbosatec/bonfire] Spine branch (PR #333) |

Wow ! This is awesome @zhangyc! Congratulations for this implementation! I loved it! 🥰
I agree with @KyleKun !
This implementation could be a great package to give support to Spine in Bonfire! bonfire_spine or thing like that!
You starting this project I will love contributing!
I really think that amazing. I didn’t know this Spine yet.

Good job @zhangyc !

**Comment by RafaelBarbosatec** [comment]
Yes! You can create a package separate that import `Bonfire` and `spine_core` you can create your mixins and implementations using `Spine`. So, this way anyone can that use `Bonfire` and want use `Spine` may add your package do enjoy your implementations.

**Comment by KyleKun** [comment]
Hi @zhangyc , I checked the package you created (https://github.com/zhangyc/bonfire_spine), is it ready for use?
@RafaelBarbosatec do you think we can add to bonfire then?

**Comment by RafaelBarbosatec** [comment]
Awesome package!
That is the idea!
Is not necessary adds this package in Bonfire package. If the user want use the spine just import bonfire and de spiner_bonfire to use it.

**Pull request closed without merging**
