### PR TITLE
Update main.dart

### PR DESCRIPTION
**Pull request by shinriyo**
# Description

Add SafeArea for main.

Screenshot 2023-09-19 at 9 33 57

Screenshot 2023-09-19 at 9 35 14

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I open this PR to the `develop` branch.
- [x] I have added a description of the change under `[next]` in `CHANGELOG.md`.
- [x] I ran `flutter format --set-exit-if-changed --dry-run .` and has success.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in `CHANGELOG.md`).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by RafaelBarbosatec** [comment]
Hi @shinriyo !
Thanks for helping.
I'm working in a new version of this example more complet and more organized. This is present in 3.0.0 branch.
If you can help there I thank you.

**Comment by shinriyo** [comment]
Screenshot 2023-09-22 at 11 28 40

The title design was changed in v3.0.0.

**Comment by shinriyo** [comment]
Screenshot 2023-09-22 at 11 32 33
If I died in Platform game, I went there.

**Comment by RafaelBarbosatec** [comment]
Thanks for contribution. But this visualization was updated.

**Pull request closed without merging**
