### PR TITLE
fix: Add mustCallSuper to GameComponent.update and onRemove

### PR DESCRIPTION
**Pull request by spydon**
# Description

Someone was confused why there code wasn't working on the discord and it was due to that they had forgotten to call `super.update`, this should make their IDE's warn them when they don't.

## Checklist

- [x] I open this PR to the `develop` branch.
- [x] I have added a description of the change under `[next]` in `CHANGELOG.md`.
- [x] I ran `flutter format --set-exit-if-changed --dry-run .` and has success.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by RafaelBarbosatec** [comment]
Thanks so much @spydon !

**Comment by spydon** [comment]
> Thanks so much @spydon !

Np! I did this PR from the browser, so I couldn't run the tests. Seems like one component is failing the pipeline, should it be calling super or should it have an ignore on it?

**Comment by RafaelBarbosatec** [comment]
I got the develop updated and fix it here.

**Comment by RafaelBarbosatec** [comment]
@spydon I still need your help to replace my collision system with Flame's. ☺️

**Pull request merged**
